import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/style/style.css";
import SideBar from '@/components/SideBar';


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} container`}>
        <div className="main">
          <SideBar></SideBar>
          <section className="col note-viewer">{ children }</section>
        </div>
      </body>
    </html>
  );
}
