import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/style/style.css";
import SideBar from '@/components/SideBar/SideBar';
import { locales } from '@/config/index.js';


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// 提供lng，便于静态生成路由
export async function generateStaticParams() {
  return locales.map(lng => ({lng}))
}

export default async function RootLayout({
  children,
  params: {
    lng
  }
}: Readonly<{
  children: React.ReactNode;
  params: any
}>) {
  return (
    <html lang={lng}>
      <body className={`${inter.className} container`}>
        <div className="main">
          <SideBar></SideBar>
          <section className="col note-viewer">{ children }</section>
        </div>
      </body>
    </html>
  );
}
